//package com.fp.backend.entity;
//
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
//import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
//
//@DynamoDBTable(tableName = "Auction")
//public class Auction {
//    private String id;
//    private String userName;
//    private String bidPrice;
//
//    public Auction(String userName, String bidPrice){
//        this.userName = userName;
//        this.bidPrice = bidPrice;
//    }
//
//    @DynamoDBHashKey
//    @DynamoDBAutoGeneratedKey
//    public String getId(){
//        return id;
//    }
//
//    @DynamoDBAttribute
//    public String getUserName(){
//        return userName;
//    }
//
//    @DynamoDBAttribute
//    public String getBidPrice(){
//        return bidPrice;
//    }
//
//
//}
